// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlOO_Tu_4ypfwtQHyG5wtzWEHVugQd4Us',
    appId: '1:124882373769:web:6f6923c94077fb482d4a58',
    messagingSenderId: '124882373769',
    projectId: 'polismart-6f6ee',
    authDomain: 'polismart-6f6ee.firebaseapp.com',
    storageBucket: 'polismart-6f6ee.appspot.com',
    measurementId: 'G-MH6D2VTE8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOMIUmX8JAx2HzL72ldpVSV8cOXXPdKWU',
    appId: '1:124882373769:android:c6a67f13fe5a133d2d4a58',
    messagingSenderId: '124882373769',
    projectId: 'polismart-6f6ee',
    storageBucket: 'polismart-6f6ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXz-ewamGtrYjjy5nM4ejJn7Kj4FPw-3U',
    appId: '1:124882373769:ios:94e99ace1a4a1b6e2d4a58',
    messagingSenderId: '124882373769',
    projectId: 'polismart-6f6ee',
    storageBucket: 'polismart-6f6ee.appspot.com',
    iosClientId: '124882373769-ki1dj3orrl96tnidqro48m1qnghkgg3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.polismartProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXz-ewamGtrYjjy5nM4ejJn7Kj4FPw-3U',
    appId: '1:124882373769:ios:b832bab60885057c2d4a58',
    messagingSenderId: '124882373769',
    projectId: 'polismart-6f6ee',
    storageBucket: 'polismart-6f6ee.appspot.com',
    iosClientId: '124882373769-04jgf7j07sk0theetjdgbjhlqag9qv8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.polismartProject.RunnerTests',
  );
}
